<a href="https://colab.research.google.com/github/KonstZiv/GoIT_datascience/blob/main/hw1_datascience_GoIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Составьте каноническое уравнение эллипсоида, проходящего через три точки A, B и C:
A(sqrt{3}; 0; sqrt{3})
B(sqrt(6); 0.5; 0)
C(1; sqrt(3)^-1; 1)
Каноническок уравнение эллипса:

$x^2/a^2 + y^2/b^2 + z^2/c^2 = 1$

Задача - найти коэфиициенты a, b, c

Учитывая что эллипс проходит чере A, B, C - имеем систему линейных уравнений:

$(1/a^2) * 3 + (1/b^2) * 0 + (1/c^2) * 3 = 1$

$(1/a^2) * 6 + (1/b^2) * 0.5 + (1/c^2) * 0 = 1$

$(1/a^2) * 1 + (1/b^2) * (1/sqrt{3}) + (1/c^2) * 1 = 1$

In [ ]:
import numpy as np

A = np.array([[3, 0, 3], [6, 0.5, 0], [1, 1/3**0.5, 1]])
b = np.array([1, 1, 1])
x = np.linalg.solve(A, b)
print(x)

[0.07044162 1.15470054 0.26289171]


In [ ]:
test_matr = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])
s= test_matr
print(s**0.5)

[[1.41421356 1.41421356 1.41421356]
 [1.73205081 1.73205081 1.73205081]
 [2.         2.         2.        ]]
