<a href="https://colab.research.google.com/github/KonstZiv/GoIT_datascience/blob/main/hw_1_datascience_GoIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
Вкладчик положил 50000 условных единиц на три разных счета в три разных банка. По первому счету выплаты составят 5% годовых, по второму – 7% годовых и по третьему 6% годовых. Известно, что через год вкладчик получил по процентам сумму в 2250 у.е. с первого и второго банка и сумму в 1400 у.е. с первого и третьего банка. Сколько условных единиц он положил на каждый счет изначально?
---

## система уравнений имеет вид:
---
x1 + x2 + x3 = 50000  x1 - вклад в банке 1

                      x2 - вклад в банке 2
                      
                      x3 - вклад в банке 3
                      
                      сумма всех вкладов равна 50000$
---
#### процентная ставка по вкладам в первом банке 5%,во втором 7%, в третьем 6%
---
0.05*x1 + 0.07*x2 + 0*x3 = 2250   через год сумма процентов с первого и второго банков составила 2250

0.05*x1 + 0*x2 + 0.06*x3 = 1400   через год сумма процентов с первого и второго банков составила 1400

In [5]:
import numpy as np
A = np.matrix("1, 1, 1; 0.05, 0.07, 0; 0.05, 0, 0.06")
b = np.array([50000, 2250, 1400])
x = np.linalg.solve(A, b)
print(x)

[10000. 25000. 15000.]


---
На складе хранятся мобильные телефоны iPhone 6, iPhone 11, iPhone 12 моделей. Всего 1328 экземпляра. Моделей iPhone 6 на 120 меньше, чем моделей iPhone 11, и на 100 больше, чем моделей iPhone 12. Сколько моделей каждого вида на складе?
---



Обозначим количество телефонов iPhone 6, iPhone 11 и iPhone 12 переменными iphone_6, iphone_11 и iphone_12 соотвественно.
Тогда условие задачи: "всего 1328 экземпляров" записывается как

iphone_6 + iphone_11 + iphone_12 = 1328

условие "Моделей iPhone 6 на 120 меньше, чем моделей iPhone 11, и на 100 больше, чем моделей iPhone 12" дает два уравнения

iphone_6 - iphone_11 = - 120

iphone_6 - iphone_12 = 100

Таким образом мы имеем матрицу коэффициентов и матрицу свободных членов следующего вида:

In [6]:
A = np.matrix("1, 1, 1; 1, -1, 0; 1, 0, -1")
b = np.array([1328, -120, 100])
x = np.linalg.solve(A, b)
print(x)

[436. 556. 336.]


---
Составьте каноническое уравнение эллипсоида, проходящего через три точки A, B и C:
A(sqrt{3}; 0; sqrt{3})
B(sqrt(6); 0.5; 0)
C(1; sqrt(3)^-1; 1)
Каноническок уравнение эллипса:

$x^2/a^2 + y^2/b^2 + z^2/c^2 = 1$

Задача - найти коэфиициенты a, b, c

---

Учитывая что эллипс проходит чере A, B, C - имеем систему линейных уравнений:

$(1/a^2) * 3 + (1/b^2) * 0 + (1/c^2) * 3 = 1$

$(1/a^2) * 6 + (1/b^2) * 0.5 + (1/c^2) * 0 = 1$

$(1/a^2) * 1 + (1/b^2) * (1/sqrt{3}) + (1/c^2) * 1 = 1$

In [7]:

A = np.array([[3, 0, 3], [6, 0.5, 0], [1, 1/3**0.5, 1]])
b = np.array([1, 1, 1])
x = np.linalg.solve(A, b)
print(x)

[0.07044162 1.15470054 0.26289171]


искомые значения $(a^2) (b^2) (c^2)$ обратны полученным $(1/a^2) (1/b^2) (1/c^2)$. Для получения искомых результатов применим групповую операцию:

In [9]:
result = 1/x
print(result)

[14.19615242  0.8660254   3.80384758]


---
Составьте уравнение параболы проходящей через заданные три точки (1,12), (3,54), (-1,2). Необходимо найти коэффициенты уравнения a,b,c

$y=a \cdot x^2 + b \cdot x + c$
---

---
для решения задачи необходимо построить систему из трех уравнений которая должна быть разрешена относительно неизвестных a, b, c. Три уравнения строятся путем подстановки заданных в условии координат трех точек в уравнеение

$a*1^2 + b* 1 + c = 12$

$a*3^2 + b* 3 + c = 54$

$a * (-1)^2$ + b * (-1) + c = 2

---


In [10]:
A = np.matrix("1, 1, 1; 9, 3, 1; 1, -1, 1")
b = np.array([12, 54, 2])
x = np.linalg.solve(A, b)
print(x)

[4. 5. 3.]


---
Составьте функцию get_polynom, которая по набору точек вида $(x_1,y_1),(x_2,y_2), \ldots, (x_{n+1}, y_{n+1})$ будет находить коэффициенты многочлена $c_i$. Таким образом функция принимает список кортежей с координатами и возвращает набор коэффициентов $c_0,c_1, \ldots c_n$
---


In [18]:
import numpy as np

def get_polynom(coords):
    b = np.matrix([coord[1] for coord in coords])
    A = np.matrix([[coord[0]**i for i in range(len(coords) - 1, -1, -1)] for coord in coords])
    return np.linalg.solve(A, b)